Repository tosc-rs/mnemos, pull requests merged in 2023-08, with the labels that each got.

#213 feat(docs): Switch to curlbash for oranda to save CI time
  scripts/install-ci-deps.sh
Labels: kind: documentation, area: tools & build

#214 Add Contributor Covenant Code of Conduct
  README.md
  code_of_conduct.md
Labels: kind: RFC

#215 docs: mention hardware and RFCs in README
  README.md
Labels: kind: documentation

#224 Fix clippy warnings and enforce -Dwarnings
  justfile
  platforms/allwinner-d1/boards/build.rs
  platforms/allwinner-d1/boards/src/bin/mq-pro.rs
  platforms/allwinner-d1/core/src/clint.rs
  platforms/allwinner-d1/core/src/drivers/spim.rs
  platforms/allwinner-d1/core/src/drivers/twi.rs
  platforms/allwinner-d1/core/src/drivers/uart.rs
  platforms/beepy/src/i2c_puppet.rs
  platforms/esp32c3-buddy/src/bin/qtpy.rs
  platforms/esp32c3-buddy/src/bin/xiao.rs
  platforms/esp32c3-buddy/src/heap.rs
  platforms/esp32c3-buddy/src/lib.rs
  platforms/melpomene/src/sim_drivers/tcp_serial.rs
  platforms/x86_64/core/src/bin/bootloader/framebuf.rs
  platforms/x86_64/core/src/bin/bootloader/main.rs
  platforms/x86_64/core/src/drivers/framebuf.rs
  platforms/x86_64/core/src/interrupt.rs
  platforms/x86_64/core/src/trace.rs
Labels: area: tools & build

#227 chore(nix): fix wrong build inputs
  shell.nix
Labels: area: tools & build

#230 bug(docs): Add netlify dry run in CI
  .github/workflows/ci.yml
  scripts/install-ci-deps.sh
  scripts/run-ci-build.sh
Labels: kind: documentation, area: tools & build

#231 bug(docs): fix netlify CI
  scripts/install-ci-deps.sh
Labels: kind: documentation, area: tools & build

#236 feat(melpo): Makes scaling an option
  platforms/melpomene/melpo-config/src/lib.rs
  platforms/melpomene/melpo.toml
  platforms/melpomene/src/sim_drivers/emb_display.rs
Labels: platform: melpomene

#262 feat(kernel/daemons/shell): Smarter redraw debouncing
  platforms/melpomene/src/main.rs
  source/kernel/src/daemons/shells.rs
Labels: area: kernel
